version: '3.9'

services:
  db:
    image: 'postgres:latest'
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: kick_auth
    ports:
      - 5432:5432

